### PR TITLE
Fix scoring reproducibility issues

### PR DESCRIPTION
**Pull request by tonywu71**

### CODE REVIEW

**Comment by aamir-s18** [comment]
hey any updates on this PR?

**Comment by tonywu71** [comment]
> hey any updates on this PR?

Yes, there are a few restructuration PRs I want to close before fixing this but it's still on top of my priority list.

**Comment by ManuelFay** [comment]
Check out #60  , should be good

**Comment by ManuelFay** [comment]
Feel free to reopen when you restructure cleanly @tonywu71 with the new format

**Pull request closed without merging**
